
server:
  port: 5994

spring:
  application:
    name: fanout-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#交换机配置
mq:
  config:
    exchange: order.fanout