server:
  port: 5993

spring:
  application:
    name: fanout-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


mq:
  config:
    #交换机配置
    exchange: order.fanout
    #队列配置
    queue:
      sms:
        name: sms_server
      push:
        name: push_server
